Blog Post Management (CRUD)
muhammadjon8/blog-platform pull request #4
Opened 2024-10-08 03:47 UTC by muhammadjon8

2024-10-09 10:35 UTC, mukhammadjon-ss requested changes
be more consistent in naming

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/entities/entity.blog.ts
naming should be proper. 
application is blog application entity is article or post. article.entity.ts, post.entity.ts

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/entities/entity.user.ts
user.entity.ts

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/express.d.ts
I think you don't need this namespace. User can be taken from token. in prev task, you implemented auth so user can be retrieved from toke. request should not include all user info

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/routes/blogRoutes.ts
why routes are not protected ?
create update, delete must be proctected

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/controllers/controller.blog.ts
blog.contoller.ts

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/services/blogs.services.ts
> +    if (blog.author.id !== author && user?.isAdmin == false) {
this can separate middleware

2024-10-09 10:35 UTC, mukhammadjon-ss commented on src/controllers/controller.blog.ts
> +  const { title, content, author } = req.body
you have to take user from token. not from request body.

2024-10-09 10:51 UTC, muhammadjon8 commented
Yeah, I will change them

On Wed, 9 Oct 2024, 15:35 Mukhammadjon Sirojiddinov, <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> be more consistent in naming
> ------------------------------
>
> On src/entities/entity.blog.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793261561>
> :
>
> naming should be proper.
> application is blog application entity is article or post.
> article.entity.ts, post.entity.ts
> ------------------------------
>
> On src/entities/entity.user.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793262180>
> :
>
> user.entity.ts
> ------------------------------
>
> On src/express.d.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793264483>
> :
>
> I think you don't need this namespace. User can be taken from token. in
> prev task, you implemented auth so user can be retrieved from toke. request
> should not include all user info
> ------------------------------
>
> On src/routes/blogRoutes.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793265909>
> :
>
> why routes are not protected ?
> create update, delete must be proctected
> ------------------------------
>
> On src/controllers/controller.blog.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793275333>
> :
>
> blog.contoller.ts
> ------------------------------
>
> In src/services/blogs.services.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793278276>
> :
>
> > +    blogId: number,
> +    author: number,
> +    title: string,
> +    content: string,
> +  ): Promise<Blog> {
> +    const blog = await this.blogRepo.findOne({
> +      where: { id: blogId },
> +      relations: ['author'],
> +    })
> +
> +    if (!blog) {
> +      throw new Error('Blog not found')
> +    }
> +    const user = await this.userRepo.findOne({where: { id: author }})
> +
> +    if (blog.author.id !== author && user?.isAdmin == false) {
>
> this can separate middleware
> ------------------------------
>
> In src/controllers/controller.blog.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1793280227>
> :
>
> > +import { Request, Response } from 'express'
> +import BlogService from '../services/blogs.services'
> +
> +export const createBlog = async (req: Request, res: Response) => {
> +  const { title, content, userId } = req.body
> +
> +  try {
> +    const blog = BlogService.createBlog(userId, title, content)
> +    res.status(201).json({ message: 'Blog created successfully', data: blog })
> +  } catch (error) {
> +    res.status(400).json({ message: error })
> +  }
> +}
> +
> +export const updateBlogById = (req: Request, res: Response) => {
> +  const { title, content, author } = req.body
>
> you have to take user from token. not from request body.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/muhammadjon8/blog-platform/pull/4#pullrequestreview-2356714917>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVQ4MLMYRQVTAQSRRENSGLDZ2UBG5AVCNFSM6AAAAABPRH2MHGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJWG4YTIOJRG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-14 13:29 UTC, mukhammadjon-ss requested changes

2024-10-14 13:29 UTC, mukhammadjon-ss commented on src/controllers/blog.controller.ts
> +  console.log('Request Body:', req.body.title)
remove console.log

2024-10-14 13:29 UTC, mukhammadjon-ss commented on src/controllers/blog.controller.ts
> +  console.log(content, title, author)
remove console.log

2024-10-14 13:36 UTC, mukhammadjon-ss requested changes

2024-10-14 13:36 UTC, mukhammadjon-ss commented on src/services/blogs.services.ts
> +    if (isAuthor) {
this is redundant. This is protected route and it has already auth middleware which checks and authenticates user.

2024-10-14 14:41 UTC, muhammadjon8 commented
Fixed!

пн, 14 окт. 2024 г. в 18:36, Mukhammadjon Sirojiddinov <
***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/services/blogs.services.ts
> <https://github.com/muhammadjon8/blog-platform/pull/4#discussion_r1799525436>
> :
>
> > +      relations: ['author'],
> +    })
> +
> +    if (!blog) {
> +      throw new Error('Blog not found')
> +    }
> +    const user = await this.userRepo.findOne({ where: { id: author } })
> +
> +    if (blog.author.id !== author && user?.isAdmin == false) {
> +      throw new Error('Unauthorized')
> +    }
> +
> +    blog.title = title
> +    blog.content = content
> +    const isAuthor = await this.userRepo.findOne({ where: { id: author } })
> +    if (isAuthor) {
>
> this is redundant. This is protected route and it has already auth
> middleware which checks and authenticates user.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/muhammadjon8/blog-platform/pull/4#pullrequestreview-2366671586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVQ4MLLWES62HKJADTWSXO3Z3PCF3AVCNFSM6AAAAABPRH2MHGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRWGY3TCNJYGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-14 14:53 UTC, merged