Comment Management (CRUD)
muhammadjon8/blog-platform pull request #8
Opened 2024-10-22 16:16 UTC by muhammadjon8

2024-10-22 17:45 UTC, muhammadjon8 commented
![image](https://github.com/user-attachments/assets/3062697a-b41d-4e2f-b540-debd003fbf85)
create comment

![image](https://github.com/user-attachments/assets/fe09a2ab-0e04-4ebe-b447-d778bce9d367)
delete comment

![image](https://github.com/user-attachments/assets/f42f65a1-a454-4432-abfc-493d2bdf2604)
update comment

![image](https://github.com/user-attachments/assets/4b9394a9-883d-44a1-ac16-39916da2f34d)
get all comments

2024-10-24 12:58 UTC, mukhammadjon-ss requested changes

2024-10-24 12:58 UTC, mukhammadjon-ss commented on src/entities/user.entity.ts
> +  comments: Comment[]
you are saving comments that user write to posts ?

2024-10-24 12:58 UTC, mukhammadjon-ss commented on src/services/comment.service.ts
> +        blog: {
comments are unique by commentId so I think you don't need to query by blogId

2024-10-24 17:11 UTC, muhammadjon8 commented on src/entities/user.entity.ts
> +  comments: Comment[]
isn't it correct

2024-10-24 17:13 UTC, muhammadjon8 commented on src/services/comment.service.ts
> +        blog: {
fixed

2024-10-29 17:22 UTC, merged